### PR TITLE
CURA-4080 Add macro and a tutorial dialog on how to install the macro

### PR DESCRIPTION
**Pull request by LipuFei**
CURA-4080

### CODE REVIEW

**Comment by thopiekar** [comment]
Nice. Could we also add a short description to the gif files?
So they are for example not called `1.gif` only, but `1 - Installation of the plugin.gif`.
I think this is handy in case we want to edit the tutorial in the future.

**Comment by LipuFei** [comment]
@thopiekar Fixed in 1b8f284

**Comment by thopiekar** [comment]
Thanks! :+1:

**Comment by LipuFei** [comment]
@thopiekar This PR is ready. Could you merge it?

**Comment by thopiekar** [comment]
@LipuFei Could you please go through @nallath 's list of recommended changes?

He pointed out a lot of things I agree on. I didn't take a close look on the QML's to be honest.

**Comment by LipuFei** [comment]
All fixed.

**Pull request merged**
