### PR TITLE
Updating master-with-pywin32 branch

### PR DESCRIPTION
**Pull request by thopiekar**

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
The STL reader can't be disabled in Cura, so I'd think it's fine to depend on it.

**Comment by thopiekar** [comment]
@Ghostkeeper I still see no reason, why hard-coding it is really needed.
Using it argumentation that it can't be disabled, it also means that whenever we are running Cura, then there is also the STL reader. Since the plugin is for Cura and only runs there, it also means that we don't need to care about STL reader as an dependency. Thus, again: Why hard-coding it??

**Comment by Ghostkeeper** [comment]
> Since the plugin is for Cura and only runs there, it also means that we don't need to care about STL reader as an dependency. Thus, again: Why hard-coding it??

Indeed, we don't need to make certain that STL reader as a dependency is present because Uranium guarantees that it is.

You wanted to have the file format detected dynamically, then? Is that what you mean?

**Comment by thopiekar** [comment]
Well, this is what I in the end did. While reading a SolidWorks file, the reader is looking for STL or 3MF readers. The current design of the plugin system does not allow anything else, like you already mentioned before.

**Pull request closed without merging**
